[connection]
tls_cert = "./certificate.pem"
tls_key = "./key.pem"

[server]
ssh_key_path = "./id_rsa"
no_client_auth = false
password_auth = true
max_auth_tries = 3

authorized_keys_file = "./authorized_keys"
